### ISSUE TITLE
why doesn't your code work on replit?

### ISSUE THREAD

**Issue by pleabargain** [watchakorn-18k/Language-Translation-App-using-AI#1]
Thanks for sharing your code! It works locally, but not on replit. Why?
https://youtu.be/jyhOD43e074

https://replit.com/@DennisGG/flet-UI-for-translation?v=1

thank you!
Khop khun krap.

**Comment by watchakorn-18k** [comment]
> ขอบคุณที่แบ่งปันรหัสของคุณ! มันใช้งานได้ในเครื่อง แต่ไม่ได้ทำซ้ำ ทำไม https://youtu.be/jyhOD43e074
> 
> https://replit.com/@DennisGG/flet-UI-for-translation?v=1
> 
> ขอบคุณ! คับคุณคร๊าบ.

@pleabargain Thank you for your interest in my project.

It works perfectly now that I've tested it on my replit.com. Again, since I'm utilizing the module, be sure to use the ```pip install -r requirements.txt ```command. Using GoogleTrans==4.0.0rc1 for language translation English is the primary language used on chatGPT.
Or you may use the command ``` pip install googletrans==4.0.0rc1 ```

![image](https://user-images.githubusercontent.com/74919942/213882221-685be40f-dae6-46cb-b3f7-1dcbb7caec8b.png)

**Comment by pleabargain** [comment]
Many thanks!
